repos:
  # ====== Secrets ======
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0 # Use latest stable tag
    hooks:
      - id: detect-secrets
        name: Detect Secrets (Baseline)
        args: ["--baseline", ".secrets.baseline"]
        additional_dependencies: ["gibberish-detector==0.1.1"]
        exclude: |
          (?x)^(
              nixos/secrets/.*\.(enc|yaml)|
              \.secrets\.baseline|
              .*\.lock
          )$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0 # Use latest stable tag
    hooks:
      - id: detect-private-key # Find private keys

  # ====== General Hygiene ======
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0 # Use latest stable tag
    hooks:
      # Git checks
      - id: check-added-large-files
        args: ["--maxkb=1024"] # 1MB max
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: forbid-new-submodules
      # File consistency
      - id: end-of-file-fixer
        exclude: "nixos/flake.lock"
      - id: trailing-whitespace
        exclude: "nixos/flake.lock"
      # File syntax
      - id: check-yaml
        exclude: ".secrets.baseline"
      - id: check-json
        exclude: '.*\.lock'
      - id: check-toml

  # ====== Nix ======
  - repo: https://github.com/astro/deadnix
    rev: v1.3.1 # Use latest stable tag
    hooks:
      - id: deadnix
        name: Find unused Nix code
